@extends('layouts.public')
@section('title', 'Legal Notices')
@section('content')
<div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
    <h1 class="text-2xl font-black text-white mb-2">Legal Notices</h1>
    <p class="text-sm text-gray-500 mb-8">Last updated: March 2026</p>

    <div class="space-y-8 text-sm text-gray-300 leading-relaxed">
        <section>
            <h2 class="text-base font-bold text-white mb-2">Simulation Disclaimer</h2>
            <p>sMLB is a fictional simulated baseball league. All players, teams, statistics, and game results are generated by the OOTP Baseball simulation engine and do not represent real MLB events, players, or outcomes.</p>
        </section>
        <section>
            <h2 class="text-base font-bold text-white mb-2">OOTP Baseball</h2>
            <p>OOTP Baseball is a product of Out of the Park Developments. sMLB One Media is not affiliated with, endorsed by, or sponsored by Out of the Park Developments or Major League Baseball.</p>
        </section>
        <section>
            <h2 class="text-base font-bold text-white mb-2">Copyright Notice</h2>
            <p>&copy; 2026 sMLB One Media. All rights reserved. Unauthorized reproduction or distribution of any content from this site is prohibited without express written consent.</p>
        </section>
        <section>
            <h2 class="text-base font-bold text-white mb-2">Trademarks</h2>
            <p>All team names, logos, and league branding displayed on this site are the property of sMLB One Media and are used for entertainment purposes only.</p>
        </section>
        <section>
            <h2 class="text-base font-bold text-white mb-2">Limitation of Liability</h2>
            <p>sMLB One Media is not liable for any damages arising from the use or inability to use this site or its content. All simulation results are for entertainment purposes only.</p>
        </section>
    </div>
</div>
@endsection
